"""direction_roadmaps.university_requirements (JSONB list)

Backend-populated, per-program facts (exams, deadline, grants, language
level, portfolio, required documents) for goal="university" direction
roadmaps — never generated by the LLM. Empty list for every other goal.
See docs/riasec-roadmap-rich-contract-plan.md, Область 8.

Revision ID: 0034
Revises: 0033
Create Date: 2026-08-06 00:00:00.000000
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0034"
down_revision: str | None = "0033"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "direction_roadmaps",
        sa.Column(
            "university_requirements",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
    )


def downgrade() -> None:
    op.drop_column("direction_roadmaps", "university_requirements")
