"""add university ovpo_code and ror_id

Revision ID: 0e1ba45c10f7
Revises: 433688aca0a1
Create Date: 2026-08-19 06:42:18.416758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e1ba45c10f7'
down_revision: Union[str, None] = '433688aca0a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('universities', sa.Column('ror_id', sa.String(length=50), nullable=True))
    op.add_column('universities', sa.Column('ovpo_code', sa.String(length=10), nullable=True))
    op.create_index(op.f('ix_universities_ovpo_code'), 'universities', ['ovpo_code'], unique=True)
    op.create_index(op.f('ix_universities_ror_id'), 'universities', ['ror_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_universities_ror_id'), table_name='universities')
    op.drop_index(op.f('ix_universities_ovpo_code'), table_name='universities')
    op.drop_column('universities', 'ovpo_code')
    op.drop_column('universities', 'ror_id')
    # ### end Alembic commands ###
