"""Add contacts and facilities to University

Revision ID: 433688aca0a1
Revises: c7e2a9f1d3b6
Create Date: 2026-08-18 10:09:09.120603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '433688aca0a1'
down_revision: Union[str, None] = 'c7e2a9f1d3b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_analysis_results_assessment_id'), 'analysis_results', type_='unique')
    op.drop_index(op.f('ix_program_directions_direction_id'), table_name='program_directions')
    op.alter_column('questions', 'text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(op.f('roadmaps_assessment_id_key'), 'roadmaps', type_='unique')
    op.drop_index(op.f('ix_roadmaps_assessment_id'), table_name='roadmaps')
    op.create_index(op.f('ix_roadmaps_assessment_id'), 'roadmaps', ['assessment_id'], unique=True)
    op.add_column('universities', sa.Column('contacts', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('universities', sa.Column('facilities', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.drop_constraint(op.f('uq_universities_slug'), 'universities', type_='unique')
    op.drop_index(op.f('ix_universities_slug'), table_name='universities')
    op.create_index(op.f('ix_universities_slug'), 'universities', ['slug'], unique=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_universities_slug'), table_name='universities')
    op.create_index(op.f('ix_universities_slug'), 'universities', ['slug'], unique=False)
    op.create_unique_constraint(op.f('uq_universities_slug'), 'universities', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_column('universities', 'facilities')
    op.drop_column('universities', 'contacts')
    op.drop_index(op.f('ix_roadmaps_assessment_id'), table_name='roadmaps')
    op.create_index(op.f('ix_roadmaps_assessment_id'), 'roadmaps', ['assessment_id'], unique=False)
    op.create_unique_constraint(op.f('roadmaps_assessment_id_key'), 'roadmaps', ['assessment_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('questions', 'text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index(op.f('ix_program_directions_direction_id'), 'program_directions', ['direction_id'], unique=False)
    op.create_unique_constraint(op.f('uq_analysis_results_assessment_id'), 'analysis_results', ['assessment_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
