"""add program name_normalized generated column and unique constraint

Revision ID: 65d65d8cb1a9
Revises: 0e1ba45c10f7
Create Date: 2026-08-19 06:49:52.486331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65d65d8cb1a9'
down_revision: Union[str, None] = '0e1ba45c10f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: ":бакалавр" (no backslash) gets read by SQLAlchemy's DDL text
    # compiler as a named bind parameter and silently rendered as NULL since
    # nothing is bound to it — `\:` escapes it back to a literal colon before
    # this reaches Postgres. Confirmed by the first attempt at this migration
    # literally shipping "(?NULL(?:..." — not a typo, a real footgun.
    op.add_column('programs', sa.Column('name_normalized', sa.Text(), sa.Computed("lower(trim(regexp_replace(name, '\\s*\\((?\\:бакалавр(?:,\\s*[^)]*)?|магистратура|практический психолог)\\)\\s*', '', 'gi')))", persisted=True), nullable=False))
    op.create_unique_constraint('uq_programs_university_name_normalized', 'programs', ['university_id', 'name_normalized'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_programs_university_name_normalized', 'programs', type_='unique')
    op.drop_column('programs', 'name_normalized')
    # ### end Alembic commands ###
