"""Add secondary goals and change count columns

Revision ID: 737ff08c158c
Revises: c126d833ed69
Create Date: 2026-08-16 11:37:28.296101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '737ff08c158c'
down_revision: Union[str, None] = 'c126d833ed69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('secondary_goals', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('assessments', sa.Column('goal_changed_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessments', 'goal_changed_count')
    op.drop_column('assessments', 'secondary_goals')
    # ### end Alembic commands ###
