"""add_roadmap_focus_summary

Revision ID: 9fe0feff92b9
Revises: d7c227f4c0b2
Create Date: 2026-08-17 09:47:49.284178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fe0feff92b9'
down_revision: Union[str, None] = 'd7c227f4c0b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roadmaps', sa.Column('focus_summary', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roadmaps', 'focus_summary')
    # ### end Alembic commands ###
