"""add program cost range/currency and fact_sources provenance

Revision ID: a27baccf4197
Revises: 65d65d8cb1a9
Create Date: 2026-08-19 08:05:18.399904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a27baccf4197'
down_revision: Union[str, None] = '65d65d8cb1a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('programs', sa.Column('cost_per_year_min', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('programs', sa.Column('cost_per_year_max', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('programs', sa.Column('cost_currency', sa.String(length=3), nullable=True))
    # server_default='{}' needed: NOT NULL on a JSONB column with no default
    # fails outright on the existing populated rows — the model's
    # `default=dict` is Python-side only (applies to new ORM inserts), not a
    # DB-level default autogenerate would pick up on its own.
    op.add_column('programs', sa.Column('fact_sources', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('universities', sa.Column('fact_sources', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('universities', 'fact_sources')
    op.drop_column('programs', 'fact_sources')
    op.drop_column('programs', 'cost_currency')
    op.drop_column('programs', 'cost_per_year_max')
    op.drop_column('programs', 'cost_per_year_min')
    # ### end Alembic commands ###
