"""remove_validity

Revision ID: b8911a00feb0
Revises: a3e28145799b
Create Date: 2026-09-21 08:09:40.779530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8911a00feb0'
down_revision: Union[str, None] = 'a3e28145799b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM questions WHERE instrument = 'validity'")
    op.drop_index(op.f('ix_certificates_profile_id'), table_name='certificates')
    op.drop_table('certificates')
    op.drop_index(op.f('ix_assessment_validity_assessment_id'), table_name='assessment_validity')
    op.drop_table('assessment_validity')
    op.drop_index(op.f('ix_validity_calibration_log_assessment_id'), table_name='validity_calibration_log')
    op.drop_table('validity_calibration_log')
    op.drop_index(op.f('ix_analysis_results_pending_review'), table_name='analysis_results', postgresql_where="(review_status = 'pending_review'::analysis_result_review_status_enum)")
    op.drop_column('analysis_results', 'validity')
    op.drop_index(op.f('ix_direction_roadmaps_program_id'), table_name='direction_roadmaps')
    op.drop_column('questions', 'validity_meta')
    op.drop_column('questions', 'validity_role')
    op.drop_index(op.f('uq_university_images_one_primary'), table_name='university_images', postgresql_where='is_primary')
    op.drop_constraint(op.f('uq_university_images_university_checksum'), 'university_images', type_='unique')
    op.drop_constraint(op.f('uq_users_google_id'), 'users', type_='unique')
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.create_unique_constraint(op.f('uq_users_google_id'), 'users', ['google_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_university_images_university_checksum'), 'university_images', ['university_id', 'checksum_sha256'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('uq_university_images_one_primary'), 'university_images', ['university_id'], unique=True, postgresql_where='is_primary')
    op.add_column('questions', sa.Column('validity_role', postgresql.ENUM('sd_key', 'infrequency', name='validity_role_enum', create_type=False), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('validity_meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_direction_roadmaps_program_id'), 'direction_roadmaps', ['program_id'], unique=False)
    op.add_column('analysis_results', sa.Column('validity', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_analysis_results_pending_review'), 'analysis_results', ['created_at'], unique=False, postgresql_where="(review_status = 'pending_review'::analysis_result_review_status_enum)")
    op.create_table('validity_calibration_log',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assessment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sd_raw', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sd_level', postgresql.ENUM('ok', 'social_desirability', 'high', name='sd_level_enum', create_type=False), autoincrement=False, nullable=False),
    sa.Column('longstring_max', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('irv', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('infrequency_failed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('careless_flag', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('traffic_light', postgresql.ENUM('green', 'yellow', 'red', name='traffic_light_enum', create_type=False), autoincrement=False, nullable=False),
    sa.Column('age_group', postgresql.ENUM('junior', 'middle', 'senior', name='age_group_enum', create_type=False), autoincrement=False, nullable=False),
    sa.Column('thresholds_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('validity_calibration_log_assessment_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('validity_calibration_log_pkey'))
    )
    op.create_index(op.f('ix_validity_calibration_log_assessment_id'), 'validity_calibration_log', ['assessment_id'], unique=False)
    op.create_table('assessment_validity',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assessment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sd_raw', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sd_level', postgresql.ENUM('ok', 'social_desirability', 'high', name='sd_level_enum', create_type=False), autoincrement=False, nullable=False),
    sa.Column('longstring_max', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('irv', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('infrequency_failed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('careless_flag', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('traffic_light', postgresql.ENUM('green', 'yellow', 'red', name='traffic_light_enum', create_type=False), autoincrement=False, nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('rt_ms', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('thresholds_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('sd_raw >= 0 AND sd_raw <= 20', name=op.f('ck_assessment_validity_sd_raw_range')),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('assessment_validity_assessment_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('assessment_validity_pkey')),
    sa.UniqueConstraint('assessment_id', name=op.f('uq_assessment_validity_assessment_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_assessment_validity_assessment_id'), 'assessment_validity', ['assessment_id'], unique=True)
    op.create_table('certificates',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('profile_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('ielts', 'unt', 'sat', 'toefl', name='certificate_type_enum', create_type=False), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name=op.f('certificates_profile_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('certificates_pkey'))
    )
    op.create_index(op.f('ix_certificates_profile_id'), 'certificates', ['profile_id'], unique=False)
    # ### end Alembic commands ###
