"""remove_validity

Revision ID: b8911a00feb0
Revises: a3e28145799b
Create Date: 2026-09-21 08:09:40.779530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b8911a00feb0'
down_revision: Union[str, None] = 'a3e28145799b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Idempotent: a database whose schema drifted from `alembic_version` (dev
    # never got the validity data model) has no `validity` enum label / tables
    # / columns to remove, and `DELETE ... = 'validity'` on such an enum is an
    # InvalidTextRepresentationError rather than a no-op.
    op.execute(
        """
        DO $$
        BEGIN
            IF EXISTS (
                SELECT 1 FROM pg_enum e JOIN pg_type t ON t.oid = e.enumtypid
                WHERE t.typname = 'question_instrument_enum' AND e.enumlabel = 'validity'
            ) THEN
                DELETE FROM questions WHERE instrument = 'validity';
            END IF;
        END $$
        """
    )
    op.execute("DROP TABLE IF EXISTS assessment_validity")
    op.execute("DROP TABLE IF EXISTS validity_calibration_log")
    op.execute("ALTER TABLE analysis_results DROP COLUMN IF EXISTS validity")
    op.execute("ALTER TABLE questions DROP COLUMN IF EXISTS validity_meta")
    op.execute("ALTER TABLE questions DROP COLUMN IF EXISTS validity_role")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('validity_role', postgresql.ENUM('sd_key', 'infrequency', name='validity_role_enum', create_type=False), autoincrement=False, nullable=True))
    op.add_column('questions', sa.Column('validity_meta', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('analysis_results', sa.Column('validity', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_table('validity_calibration_log',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assessment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sd_raw', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sd_level', postgresql.ENUM('ok', 'social_desirability', 'high', name='sd_level_enum', create_type=False), autoincrement=False, nullable=False),
    sa.Column('longstring_max', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('irv', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('infrequency_failed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('careless_flag', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('traffic_light', postgresql.ENUM('green', 'yellow', 'red', name='traffic_light_enum', create_type=False), autoincrement=False, nullable=False),
    sa.Column('age_group', postgresql.ENUM('junior', 'middle', 'senior', name='age_group_enum', create_type=False), autoincrement=False, nullable=False),
    sa.Column('thresholds_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('validity_calibration_log_assessment_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('validity_calibration_log_pkey'))
    )
    op.create_index(op.f('ix_validity_calibration_log_assessment_id'), 'validity_calibration_log', ['assessment_id'], unique=False)
    op.create_table('assessment_validity',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('assessment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sd_raw', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sd_level', postgresql.ENUM('ok', 'social_desirability', 'high', name='sd_level_enum', create_type=False), autoincrement=False, nullable=False),
    sa.Column('longstring_max', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('irv', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('infrequency_failed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('careless_flag', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('traffic_light', postgresql.ENUM('green', 'yellow', 'red', name='traffic_light_enum', create_type=False), autoincrement=False, nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('rt_ms', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('thresholds_version', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('sd_raw >= 0 AND sd_raw <= 20', name=op.f('ck_assessment_validity_sd_raw_range')),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], name=op.f('assessment_validity_assessment_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('assessment_validity_pkey')),
    sa.UniqueConstraint('assessment_id', name=op.f('uq_assessment_validity_assessment_id'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_assessment_validity_assessment_id'), 'assessment_validity', ['assessment_id'], unique=True)
    # ### end Alembic commands ###
