"""Add goal overlays table

Revision ID: c126d833ed69
Revises: 0042
Create Date: 2026-08-16 11:07:04.572134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c126d833ed69'
down_revision: Union[str, None] = '0042'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal_overlays',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('goal', postgresql.ENUM('explore', 'profession', 'university', 'unsure', name='assessment_goal_enum', create_type=False), nullable=False),
    sa.Column('scenario', sa.String(length=10), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'goal', name='uq_goal_overlay_assessment_goal')
    )
    op.create_index(op.f('ix_goal_overlays_assessment_id'), 'goal_overlays', ['assessment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_goal_overlays_assessment_id'), table_name='goal_overlays')
    op.drop_table('goal_overlays')
    # ### end Alembic commands ###
