"""
Raw RIASEC profession → Holland-code reference data.

Source: "Вопросы R.md", attached by the user — 160 lines transcribed from a
`Profession.java` seed (`title` + `hollandCode` only, no description/industry/
education level). Kept exactly as given, grouped by section in source order,
including the cross-section and in-section duplicates the source itself has
(e.g. "Archaeologist" appears under both Realistic and Investigative;
"Abstractor" appears twice under Conventional) — this file is the traceable
source of truth, deduplication happens in seed_riasec_directions.py, not here.

Section order matters: scripts/seed_riasec_directions.py dedupes by title,
first occurrence wins. This is what deterministically resolves the one real
data conflict in the source — "Psychologist" is listed as both IES
(Investigative) and SEI (Social) — Investigative comes first below, so IES
is what gets seeded. Documented here, not special-cased in code.
"""

PROFESSIONS: list[dict] = [
    # Realistic (26)
    {"section": "Realistic", "title": "Air Traffic Controller", "holland_code": "SER"},
    {"section": "Realistic", "title": "Archaeologist", "holland_code": "IRE"},
    {"section": "Realistic", "title": "Athletic Trainer", "holland_code": "SRE"},
    {"section": "Realistic", "title": "Cartographer", "holland_code": "IRE"},
    {"section": "Realistic", "title": "Commercial Airline Pilot", "holland_code": "RIE"},
    {"section": "Realistic", "title": "Commercial Drafter", "holland_code": "IRE"},
    {"section": "Realistic", "title": "Dental Technician", "holland_code": "REI"},
    {"section": "Realistic", "title": "Farm Manager", "holland_code": "ESR"},
    {"section": "Realistic", "title": "Fish and Game Warden", "holland_code": "RES"},
    {"section": "Realistic", "title": "Floral Designer", "holland_code": "RAE"},
    {"section": "Realistic", "title": "Forester", "holland_code": "RIS"},
    {"section": "Realistic", "title": "Geodetic Surveyor", "holland_code": "IRE"},
    {"section": "Realistic", "title": "Industrial Arts Teacher", "holland_code": "IER"},
    {"section": "Realistic", "title": "Laboratory Technician", "holland_code": "RIE"},
    {"section": "Realistic", "title": "Landscape Architect", "holland_code": "AIR"},
    {"section": "Realistic", "title": "Mechanical Engineer", "holland_code": "RIS"},
    {"section": "Realistic", "title": "Optician", "holland_code": "REI"},
    {"section": "Realistic", "title": "Petroleum Geologist", "holland_code": "RIE"},
    {"section": "Realistic", "title": "Police Officer", "holland_code": "SER"},
    {"section": "Realistic", "title": "Practical Nurse", "holland_code": "SER"},
    {"section": "Realistic", "title": "Property Manager", "holland_code": "ESR"},
    {"section": "Realistic", "title": "Recreation Manager", "holland_code": "SER"},
    {"section": "Realistic", "title": "Service Manager", "holland_code": "ERS"},
    {"section": "Realistic", "title": "Software Technician", "holland_code": "RCI"},
    {"section": "Realistic", "title": "Ultrasound Technologist", "holland_code": "RSI"},
    {"section": "Realistic", "title": "Vocational Rehabilitation Consultant", "holland_code": "ESR"},

    # Investigative (28)
    {"section": "Investigative", "title": "Actuary", "holland_code": "ISE"},
    {"section": "Investigative", "title": "Agronomist", "holland_code": "IRS"},
    {"section": "Investigative", "title": "Anesthesiologist", "holland_code": "IRS"},
    {"section": "Investigative", "title": "Anthropologist", "holland_code": "IRE"},
    {"section": "Investigative", "title": "Archaeologist", "holland_code": "IRE"},
    {"section": "Investigative", "title": "Biochemist", "holland_code": "IRS"},
    {"section": "Investigative", "title": "Biologist", "holland_code": "IRE"},
    {"section": "Investigative", "title": "Chemical Engineer", "holland_code": "IRE"},
    {"section": "Investigative", "title": "Chemist", "holland_code": "IRE"},
    {"section": "Investigative", "title": "Computer Systems Analyst", "holland_code": "IER"},
    {"section": "Investigative", "title": "Dentist", "holland_code": "ISR"},
    {"section": "Investigative", "title": "Ecologist", "holland_code": "IRE"},
    {"section": "Investigative", "title": "Economist", "holland_code": "IAS"},
    {"section": "Investigative", "title": "Electrical Engineer", "holland_code": "IRE"},
    {"section": "Investigative", "title": "Geologist", "holland_code": "IRE"},
    {"section": "Investigative", "title": "Horticulturist", "holland_code": "IRS"},
    {"section": "Investigative", "title": "Mathematician", "holland_code": "IRE"},
    {"section": "Investigative", "title": "Medical Technologist", "holland_code": "ISA"},
    {"section": "Investigative", "title": "Meteorologist", "holland_code": "IRS"},
    {"section": "Investigative", "title": "Nurse Practitioner", "holland_code": "ISA"},
    {"section": "Investigative", "title": "Pharmacist", "holland_code": "IES"},
    {"section": "Investigative", "title": "Physician, General Practice", "holland_code": "ISE"},
    {"section": "Investigative", "title": "Psychologist", "holland_code": "IES"},
    {"section": "Investigative", "title": "Research Analyst", "holland_code": "IRC"},
    {"section": "Investigative", "title": "Statistician", "holland_code": "IRE"},
    {"section": "Investigative", "title": "Surgeon", "holland_code": "IRA"},
    {"section": "Investigative", "title": "Technical Writer", "holland_code": "IRS"},
    {"section": "Investigative", "title": "Veterinarian", "holland_code": "IRS"},

    # Artistic (23)
    {"section": "Artistic", "title": "Actor", "holland_code": "AES"},
    {"section": "Artistic", "title": "Advertising Art Director", "holland_code": "AES"},
    {"section": "Artistic", "title": "Advertising Manager", "holland_code": "ASE"},
    {"section": "Artistic", "title": "Architect", "holland_code": "AIR"},
    {"section": "Artistic", "title": "Art Teacher", "holland_code": "ASE"},
    {"section": "Artistic", "title": "Artist", "holland_code": "ASI"},
    {"section": "Artistic", "title": "Copy Writer", "holland_code": "ASI"},
    {"section": "Artistic", "title": "Dance Instructor", "holland_code": "AER"},
    {"section": "Artistic", "title": "Drama Coach", "holland_code": "ASE"},
    {"section": "Artistic", "title": "English Teacher", "holland_code": "ASE"},
    {"section": "Artistic", "title": "Entertainer/Performer", "holland_code": "AES"},
    {"section": "Artistic", "title": "Fashion Illustrator", "holland_code": "ASR"},
    {"section": "Artistic", "title": "Interior Designer", "holland_code": "AES"},
    {"section": "Artistic", "title": "Intelligence Research Specialist", "holland_code": "AEI"},
    {"section": "Artistic", "title": "Journalist/Reporter", "holland_code": "ASE"},
    {"section": "Artistic", "title": "Landscape Architect", "holland_code": "AIR"},
    {"section": "Artistic", "title": "Librarian", "holland_code": "SAI"},
    {"section": "Artistic", "title": "Medical Illustrator", "holland_code": "AIE"},
    {"section": "Artistic", "title": "Museum Curator", "holland_code": "AES"},
    {"section": "Artistic", "title": "Music Teacher", "holland_code": "ASI"},
    {"section": "Artistic", "title": "Photographer", "holland_code": "AES"},
    {"section": "Artistic", "title": "Writer", "holland_code": "ASI"},
    {"section": "Artistic", "title": "Graphic Designer", "holland_code": "AES"},

    # Social (26)
    {"section": "Social", "title": "City Manager", "holland_code": "SEC"},
    {"section": "Social", "title": "Clinical Dietitian", "holland_code": "SIE"},
    {"section": "Social", "title": "College/University Faculty", "holland_code": "SEI"},
    {"section": "Social", "title": "Community Org. Director", "holland_code": "SEA"},
    {"section": "Social", "title": "Consumer Affairs Director", "holland_code": "SER"},
    {"section": "Social", "title": "Counselor/Therapist", "holland_code": "SAE"},
    {"section": "Social", "title": "Historian", "holland_code": "SEI"},
    {"section": "Social", "title": "Hospital Administrator", "holland_code": "SER"},
    {"section": "Social", "title": "Psychologist", "holland_code": "SEI"},
    {"section": "Social", "title": "Insurance Claims Examiner", "holland_code": "SIE"},
    {"section": "Social", "title": "Librarian", "holland_code": "SAI"},
    {"section": "Social", "title": "Medical Assistant", "holland_code": "SCR"},
    {"section": "Social", "title": "Minister/Priest/Rabbi", "holland_code": "SAI"},
    {"section": "Social", "title": "Paralegal", "holland_code": "SCE"},
    {"section": "Social", "title": "Park Naturalist", "holland_code": "SEI"},
    {"section": "Social", "title": "Physical Therapist", "holland_code": "SIE"},
    {"section": "Social", "title": "Police Officer", "holland_code": "SER"},
    {"section": "Social", "title": "Probation and Parole Officer", "holland_code": "SEC"},
    {"section": "Social", "title": "Real Estate Appraiser", "holland_code": "SCE"},
    {"section": "Social", "title": "Recreation Director", "holland_code": "SER"},
    {"section": "Social", "title": "Registered Nurse", "holland_code": "SIA"},
    {"section": "Social", "title": "Teacher", "holland_code": "SAE"},
    {"section": "Social", "title": "Social Worker", "holland_code": "SEA"},
    {"section": "Social", "title": "Speech Pathologist", "holland_code": "SAI"},
    {"section": "Social", "title": "Vocational-Rehab. Counselor", "holland_code": "SEC"},
    {"section": "Social", "title": "Volunteer Services Director", "holland_code": "SEC"},

    # Enterprising (28)
    {"section": "Enterprising", "title": "Advertising Executive", "holland_code": "ESA"},
    {"section": "Enterprising", "title": "Advertising Sales Rep", "holland_code": "ESR"},
    {"section": "Enterprising", "title": "Banker/Financial Planner", "holland_code": "ESR"},
    {"section": "Enterprising", "title": "Branch Manager", "holland_code": "ESA"},
    {"section": "Enterprising", "title": "Business Manager", "holland_code": "ESC"},
    {"section": "Enterprising", "title": "Buyer", "holland_code": "ESA"},
    {"section": "Enterprising", "title": "Chamber of Commerce Exec", "holland_code": "ESA"},
    {"section": "Enterprising", "title": "Credit Analyst", "holland_code": "ESA"},
    {"section": "Enterprising", "title": "Customer Service Manager", "holland_code": "ESA"},
    {"section": "Enterprising", "title": "Education & Training Manager", "holland_code": "EIS"},
    {"section": "Enterprising", "title": "Emergency Medical Technician", "holland_code": "ESI"},
    {"section": "Enterprising", "title": "Entrepreneur", "holland_code": "ESA"},
    {"section": "Enterprising", "title": "Foreign Service Officer", "holland_code": "ESA"},
    {"section": "Enterprising", "title": "Funeral Director", "holland_code": "ESR"},
    {"section": "Enterprising", "title": "Insurance Manager", "holland_code": "ESC"},
    {"section": "Enterprising", "title": "Interpreter", "holland_code": "ESA"},
    {"section": "Enterprising", "title": "Lawyer/Attorney", "holland_code": "ESA"},
    {"section": "Enterprising", "title": "Lobbyist", "holland_code": "ESA"},
    {"section": "Enterprising", "title": "Office Manager", "holland_code": "ESR"},
    {"section": "Enterprising", "title": "Personnel Recruiter", "holland_code": "ESR"},
    {"section": "Enterprising", "title": "Politician", "holland_code": "ESA"},
    {"section": "Enterprising", "title": "Public Relations Rep", "holland_code": "EAS"},
    {"section": "Enterprising", "title": "Retail Store Manager", "holland_code": "ESR"},
    {"section": "Enterprising", "title": "Sales Manager", "holland_code": "ESA"},
    {"section": "Enterprising", "title": "Sales Representative", "holland_code": "ERS"},
    {"section": "Enterprising", "title": "Social Service Director", "holland_code": "ESA"},
    {"section": "Enterprising", "title": "Stockbroker", "holland_code": "ESI"},
    {"section": "Enterprising", "title": "Tax Accountant", "holland_code": "ECS"},

    # Conventional (29 — source lists "Abstractor" twice, kept as-is for fidelity)
    {"section": "Conventional", "title": "Abstractor", "holland_code": "CSI"},
    {"section": "Conventional", "title": "Abstractor", "holland_code": "CSI"},
    {"section": "Conventional", "title": "Accountant", "holland_code": "CSE"},
    {"section": "Conventional", "title": "Administrative Assistant", "holland_code": "ESC"},
    {"section": "Conventional", "title": "Budget Analyst", "holland_code": "CER"},
    {"section": "Conventional", "title": "Business Programmer", "holland_code": "CRI"},
    {"section": "Conventional", "title": "Business Teacher", "holland_code": "CSE"},
    {"section": "Conventional", "title": "Catalog Librarian", "holland_code": "CSE"},
    {"section": "Conventional", "title": "Claims Adjuster", "holland_code": "SEC"},
    {"section": "Conventional", "title": "Computer Operator", "holland_code": "CSR"},
    {"section": "Conventional", "title": "Congressional-District Aide", "holland_code": "CES"},
    {"section": "Conventional", "title": "Cost Accountant", "holland_code": "CES"},
    {"section": "Conventional", "title": "Court Reporter", "holland_code": "CSE"},
    {"section": "Conventional", "title": "Credit Manager", "holland_code": "ESC"},
    {"section": "Conventional", "title": "Customs Inspector", "holland_code": "CEI"},
    {"section": "Conventional", "title": "Editorial Assistant", "holland_code": "CSI"},
    {"section": "Conventional", "title": "Elementary School Teacher", "holland_code": "SEC"},
    {"section": "Conventional", "title": "Financial Analyst", "holland_code": "CSI"},
    {"section": "Conventional", "title": "Insurance Manager", "holland_code": "ESC"},
    {"section": "Conventional", "title": "Insurance Underwriter", "holland_code": "CSE"},
    {"section": "Conventional", "title": "Internal Auditor", "holland_code": "ICR"},
    {"section": "Conventional", "title": "Kindergarten Teacher", "holland_code": "ESC"},
    {"section": "Conventional", "title": "Medical Records Technician", "holland_code": "CSE"},
    {"section": "Conventional", "title": "Museum Registrar", "holland_code": "CSE"},
    {"section": "Conventional", "title": "Paralegal", "holland_code": "SCE"},
    {"section": "Conventional", "title": "Safety Inspector", "holland_code": "RCS"},
    {"section": "Conventional", "title": "Tax Accountant", "holland_code": "ECS"},
    {"section": "Conventional", "title": "Tax Consultant", "holland_code": "CES"},
    {"section": "Conventional", "title": "Travel Agent", "holland_code": "ECS"},
]

assert len(PROFESSIONS) == 160, f"expected 160 raw rows (per source), got {len(PROFESSIONS)}"
