"""Direct specialty -> profession mapping. Replaces the keyword/category
bridge entirely (scripts/specialty_category_lookup.py, removed) — that
system kept breaking because it inferred a profession match from a shared
CATEGORY, and categories necessarily blur together things (a style word like
"инженерия" fit a dozen unrelated jobs; a group's own title sometimes lied
about its contents). This file instead says, for each real specialty name in
university-data/*.py, exactly which profession(s) from scripts/riasec_professions.py
it actually trains someone for — hand-authored, not inferred by substring
matching. A specialty can list more than one profession (e.g. "Хореография"
trains a "Хореограф" who could also become a "Преподаватель искусства"); a
program with no clear professional match should not be force-fit — leave it
out of SPECIALTY_TO_PROFESSIONS and it will show up in
scripts/seed_kz_universities.py's "unmapped" report for manual review.

GARBAGE_SPECIALTIES holds source-data entries that are not real specialties
at all — a partner university's own name listed as if it were a program
under "Двойные дипломы" (e.g. "Coventry University"), a purely
administrative unit ("Военная кафедра"), or a faculty label with no
specific-enough subject to map anywhere ("Технический факультет"). These are
skipped entirely during seeding rather than forced into a category.
"""

GARBAGE_SPECIALTIES: set[str] = {
    "BLCU (Пекинский университет языков и культуры)",
    "Coventry University",
    "Sofia University",
    "UIBE (University of International Business and Economics)",
    "Военная кафедра",
    "Высший колледж ЕНУ",
    "Начальная военная подготовка",
    "Технический факультет",
    "Физико-технический",
    "Естественных наук",
    "Социальных наук",
    "Гуманитарные направления",
    "Юридические направления",
}

# specialty name -> list of profession slugs (see scripts/riasec_professions.py)
SPECIALTY_TO_PROFESSIONS: dict[str, list[str]] = {
    # --- Medicine / pharmacy ---
    '6-летняя программа "Doctor of Medicine" (Undergraduate Medical Program)': ["vrach-obschey-praktiki"],
    "Bachelor in Nursing": ["meditsinskaya-sestra-medbrat"],
    "Bachelor of Medical Science": ["vrach-obschey-praktiki"],
    "Общая медицина": ["vrach-obschey-praktiki"],
    "Стоматология": ["stomatolog"],
    "Педиатрия": ["vrach-obschey-praktiki"],
    "Фармация": ["farmatsevt"],
    "Технология фармацевтического производства": ["farmatsevt"],
    "Сестринское дело": ["meditsinskaya-sestra-medbrat"],
    "Сестринское дело (включая Кинезитерапию, Эрготерапию)": ["meditsinskaya-sestra-medbrat", "reabilitolog-ergoterapevt"],
    "Общественное здравоохранение": ["vrach-obschey-praktiki"],
    "Общественное здоровье": ["vrach-obschey-praktiki"],
    "Медико-профилактическое дело": ["vrach-obschey-praktiki"],
    "Социальная работа в здравоохранении": ["sotsialnyy-rabotnik"],
    "Клиническая психология": ["psiholog-konsultant"],
    "Медицинская биология": ["biolog"],

    # --- Biology / ecology / agriculture ---
    "Biological Sciences": ["biolog"],
    "Ecology and nature management": ["inzhener-ekolog"],
    "Агрономия": ["agronom"],
    "Ветеринарная санитария": ["veterinar"],
    "Ветеринарная безопасность": ["veterinar"],
    "Технология производства продуктов животноводства": ["upravlyayuschiy-fermerskim-hozyaystvom", "veterinar"],
    "Биология": ["biolog"],
    "Биотехнология": ["issledovatel-v-oblasti-biotehnologiy"],
    "Биофизика": ["biolog"],
    "Биоинженерия и биоинформатика": ["issledovatel-v-oblasti-biotehnologiy"],
    "Водное хозяйство и мелиорация": ["agronom"],
    "Наука о растениях и технологии": ["agronom"],
    "Природопользование": ["inzhener-ekolog"],
    "Экология": ["inzhener-ekolog", "meteorolog"],
    "Экология и природопользование": ["inzhener-ekolog"],
    "Окружающая среда и устойчивое развитие": ["inzhener-ekolog"],
    "Аквакультура и водные биоресурсы": ["veterinar"],
    "Охотоведение и звероводство": ["lesnichiy"],
    "Плодоовощеводство и агропочвоведение": ["agronom"],
    "Почвоведение и агрохимия": ["agronom"],
    "Аграрный факультет": ["agronom"],
    "Аграрная техника и технология": ["inzhener-mehanik"],
    "Инженерная экология": ["inzhener-ekolog"],

    # --- Sport ---
    "Физическая культура и спорт": ["trener-po-sportu"],
    "Адаптивная физическая культура и спорт": ["trener-po-sportu", "reabilitolog-ergoterapevt"],
    "Подготовка учителей физической культуры": ["trener-po-sportu", "shkolnyy-uchitel"],
    "Подготовка учителя физической культуры и инструктора-методиста по массовой физкультурно-оздоровительной работе": ["trener-po-sportu"],
    "Подготовка учителя физической культуры и тренера по конным видам спорта": ["trener-po-sportu"],
    "Подготовка учителя физической культуры и тренера по национальным видам спорта, спортивным играм": ["trener-po-sportu"],
    "Учитель физической культуры и тренер по видам спорта": ["trener-po-sportu"],
    "Фитнес и рекреация": ["trener-po-sportu"],
    "Педагог — тренер по Qazaq kuresi": ["trener-po-sportu"],
    "Педагог — тренер по настольным видам спорта (шахматы)": ["trener-po-sportu"],
    "Рекреация и спортивно-оздоровительный туризм": ["trener-po-sportu", "gid-ekskursovod"],

    # --- Psychology / pedagogy / humanities ---
    "Педагогика и психология": ["shkolnyy-uchitel", "psiholog-konsultant"],
    "Педагогика и психология с полиязычием": ["shkolnyy-uchitel"],
    "Дефектология": ["logoped"],
    "Социальная педагогика": ["sotsialnyy-rabotnik"],
    "Социальная педагогика и самопознание": ["sotsialnyy-rabotnik"],
    "Дошкольное образование и воспитание": ["vospitatel-detskogo-sada"],
    "Дошкольное обучение и воспитание": ["vospitatel-detskogo-sada"],
    "Начальное образование": ["shkolnyy-uchitel"],
    "Начальное образование на английском языке": ["shkolnyy-uchitel"],
    "Начальное образование с информационно-коммуникационными технологиями": ["shkolnyy-uchitel"],
    "Педагогика и методика начального обучения": ["shkolnyy-uchitel"],
    "Pedagogy and methodology of primary education": ["shkolnyy-uchitel"],
    "Preschool education and upbringing": ["vospitatel-detskogo-sada"],
    "Учитель информатики": ["shkolnyy-uchitel"],
    "Учитель информатики/математики и др.": ["shkolnyy-uchitel"],
    "Учитель математики": ["shkolnyy-uchitel"],
    "Психология": ["psiholog-konsultant", "psiholog-issledovatel"],
    "Psychology": ["psiholog-konsultant"],
    "Организационная психология": ["psiholog-issledovatel", "hr-menedzher"],
    "Психологические особенности развития личности": ["psiholog-konsultant"],
    "Психологическое консультирование": ["psiholog-konsultant"],
    "Когнитивные науки": ["psiholog-issledovatel"],
    "История": ["arheolog", "prepodavatel-vuza"],
    "История-История": ["shkolnyy-uchitel"],
    "География": ["shkolnyy-uchitel"],
    "География-История": ["shkolnyy-uchitel"],
    "Филология": ["biznes-perevodchik"],
    "Филологический": ["biznes-perevodchik"],
    "Подготовка учителей биологии": ["shkolnyy-uchitel"],
    "Социальная работа": ["sotsialnyy-rabotnik", "spetsialist-po-rabote-s-molodezhyu"],
    "Философия": ["prepodavatel-vuza"],
    "Социология": ["psiholog-issledovatel"],
    "Иностранные языки": ["shkolnyy-uchitel"],
    "Иностранный язык: два иностранных языка": ["shkolnyy-uchitel"],
    "Казахский язык и литература": ["shkolnyy-uchitel"],
    "Русский язык и литература": ["shkolnyy-uchitel"],
    "Иностранная филология": ["biznes-perevodchik", "shkolnyy-uchitel"],
    "Иностранная филология (восточные языки: китайский, корейский, японский, арабский, турецкий)": ["biznes-perevodchik"],
    "Иностранная филология (европейские языки: английский/французский, испанский, немецкий)": ["biznes-perevodchik"],
    "World Languages, Literature and Culture": ["shkolnyy-uchitel"],
    "Applied Linguistics": ["biznes-perevodchik"],
    "Прикладная лингвистика": ["biznes-perevodchik"],
    "Казахский-английский языки и лингвистика": ["biznes-perevodchik"],
    "Тюркология": ["biznes-perevodchik"],
    "Востоковедение": ["biznes-perevodchik", "diplomat"],
    "Религиоведение": ["prepodavatel-vuza"],
    "Исламоведение": ["prepodavatel-vuza"],
    "Теология": ["prepodavatel-vuza"],
    "Библиотечное дело": ["bibliotekar", "arhivarius"],
    "Культурно-досуговая работа": ["sotsialnyy-rabotnik"],
    "Профессиональное обучение": ["shkolnyy-uchitel"],
    "Anthropology": ["arheolog"],
    "Sociology": ["psiholog-issledovatel"],
    "History": ["arheolog", "prepodavatel-vuza"],

    # --- Law / public administration / international relations ---
    "Law (Юриспруденция)": ["yurist-advokat"],
    "Юриспруденция": ["yurist-advokat"],
    "Юриспруденция: государственное управление": ["gosudarstvennyy-sluzhaschiy"],
    "Юриспруденция: правоохранительная деятельность": ["politseyskiy"],
    "Юриспруденция: предпринимательское право": ["yurist-advokat"],
    "Цифровая юриспруденция": ["yurist-advokat"],
    "Юридическая деятельность в сфере защиты прав человека": ["yurist-advokat"],
    "Юридический": ["yurist-advokat"],
    "International Law (Международное право)": ["yurist-advokat", "diplomat"],
    "International law": ["yurist-advokat"],
    "Международное право": ["yurist-advokat"],
    "Международное право и безопасность": ["diplomat"],
    "Международное право, юрист-международник со знанием двух иностранных языков": ["diplomat", "yurist-advokat"],
    "Международное экономическое право": ["yurist-advokat"],
    "Корпоративное право": ["yurist-advokat"],
    "Правовое обеспечение экономической безопасности": ["yurist-advokat"],
    "Правовое регулирование экономики": ["yurist-advokat"],
    "Право и правоохранительная деятельность": ["politseyskiy"],
    "Правоохранительная деятельность": ["politseyskiy"],
    "Следственно-криминалистическая деятельность": ["politseyskiy"],
    "Судебно-прокурорская деятельность": ["yurist-advokat"],
    "Таможенное дело": ["spetsialist-po-tamozhennomu-delu"],
    "Таможенное оформление и таможенный контроль": ["spetsialist-po-tamozhennomu-delu"],
    "Государственное и местное управление": ["gosudarstvennyy-sluzhaschiy"],
    "Государственное и региональное управление": ["gosudarstvennyy-sluzhaschiy"],
    "Государственное управление": ["gosudarstvennyy-sluzhaschiy"],
    "Digital Public Administration": ["gosudarstvennyy-sluzhaschiy"],
    "Регионоведение": ["diplomat"],
    "Международные отношения": ["diplomat"],
    "Международных отношений": ["diplomat"],
    "International Relations": ["diplomat"],
    "Political Science and International Relations": ["diplomat", "gosudarstvennyy-sluzhaschiy"],
    "Политология": ["gosudarstvennyy-sluzhaschiy"],
    "Журналистики и политологии": ["zhurnalist"],
    "Translation Studies": ["biznes-perevodchik"],
    "Linguistics (TESOL) and Translation Technologies": ["biznes-perevodchik"],
    "Переводческое дело": ["biznes-perevodchik"],
    "Переводческое дело (английский, французский, испанский, немецкий, китайский, корейский, арабский)": ["biznes-perevodchik"],
    "Переводческое дело (восточные языки)": ["biznes-perevodchik"],
    "Переводческое дело (западные языки)": ["biznes-perevodchik"],
    "Переводческое дело (китайский, турецкий)": ["biznes-perevodchik"],
    "Межкультурно-коммуникативный перевод": ["biznes-perevodchik"],

    # --- Finance / economics ---
    "Economics": ["ekonomist-analitik"],
    "Economy": ["ekonomist-analitik"],
    "Экономика": ["ekonomist-analitik"],
    "Экономика и менеджмент": ["ekonomist-analitik"],
    "Экономика и менеджмент (по отраслям)": ["ekonomist-analitik"],
    "Экономический": ["ekonomist-analitik"],
    "Экономический факультет": ["ekonomist-analitik"],
    "Бизнес-экономика": ["ekonomist-analitik"],
    "Мировая экономика": ["ekonomist-analitik"],
    "Информационный инжиниринг в экономике": ["ekonomist-analitik"],
    "Финансы": ["finansovyy-konsultant"],
    "Finance": ["finansovyy-konsultant"],
    "Финансы и Экономика": ["finansovyy-konsultant", "ekonomist-analitik"],
    "Финансы и инвестиции": ["finansovyy-konsultant"],
    "Финансовая Математика": ["finansovyy-analitik", "aktuariy"],
    "Финансовая аналитика": ["finansovyy-analitik", "kreditnyy-analitik"],
    "Финансовые рынки и финансовые институты": ["birzhevoy-broker", "strahovoy-agent", "strahovoy-anderrayter"],
    "Корпоративные финансы": ["finansovyy-analitik"],
    "Бухгалтерский учет и аудит": ["buhgalter", "auditor"],
    "Бухгалтерский учет и финансы": ["buhgalter", "nalogovyy-konsultant"],
    "Учет и Аудит": ["buhgalter", "auditor"],
    "Учет и аудит": ["buhgalter", "auditor"],
    "Учет и аудит по ACCA": ["buhgalter", "auditor"],
    "Учёт и аудит": ["buhgalter", "auditor"],
    "Accounting with AI": ["buhgalter"],
    "Economics and Data Science": ["analitik-dannyh", "ekonomist-analitik"],
    "Экономика и наука о данных": ["ekonomist-analitik", "analitik-dannyh"],

    # --- Business / management / tourism ---
    "Business Administration (BBA)": ["predprinimatel"],
    "Business Management/Administration": ["predprinimatel"],
    "Management": ["menedzher-po-prodazham"],
    "Industrial management": ["menedzher-po-prodazham"],
    "Менеджмент": ["menedzher-po-prodazham", "rieltor"],
    "Менеджмент и маркетинг": ["direktor-po-marketingu"],
    "Менеджмент предприятий": ["predprinimatel"],
    "Глобальный менеджмент": ["predprinimatel"],
    "Инновационный менеджмент": ["predprinimatel"],
    "Бизнес администрирование": ["predprinimatel", "sekretar-deloproizvoditel", "spetsialist-po-kadrovomu-deloproizvodstvu"],
    "Бизнес и управление": ["predprinimatel"],
    "Бизнес-предпринимательство и инновации": ["predprinimatel"],
    "Международный бизнес": ["predprinimatel"],
    "Eurasian Business (двойной диплом с HKUST)": ["predprinimatel"],
    "Электронный бизнес": ["predprinimatel"],
    "Digital бизнес": ["predprinimatel"],
    "Бизнес право": ["yurist-advokat"],
    "Бизнес-право": ["yurist-advokat"],
    "IT в бизнесе": ["sistemnyy-analitik"],
    "IT (Information Technology, бизнес-профиль)": ["sistemnyy-analitik"],
    "IT-менеджмент": ["sistemnyy-analitik"],
    "IT Management": ["sistemnyy-analitik"],
    "Информационные бизнес-системы": ["sistemnyy-analitik"],
    "Информационные системы в бизнесе": ["sistemnyy-analitik"],
    "IT Entrepreneurship": ["predprinimatel"],
    "AI Business": ["spetsialist-po-iskusstvennomu-intellektu"],
    "Логистика (по отраслям)": ["direktor-po-logistike", "spetsialist-po-zakupkam"],
    "Логистика на транспорте": ["direktor-po-logistike"],
    "Logistics (Логистика)": ["direktor-po-logistike"],
    "Производственная логистика": ["direktor-po-logistike"],
    "Транспортная логистика": ["direktor-po-logistike"],
    "Цифровая логистика": ["direktor-po-logistike"],
    "Организация перевозок и логистика на транспорте": ["direktor-po-logistike"],
    "Организация авиационных перевозок и логистика": ["direktor-po-logistike", "aviadispetcher"],
    "Туризм": ["gid-ekskursovod"],
    "Международный туризм": ["gid-ekskursovod"],
    "Tourism": ["gid-ekskursovod"],
    "Travel Management and Data Analysis": ["gid-ekskursovod"],
    "Гостеприимство": ["upravlyayuschiy-otelem-restoranom"],
    "Hospitality": ["upravlyayuschiy-otelem-restoranom"],
    "Туризм и гостеприимство": ["upravlyayuschiy-otelem-restoranom", "gid-ekskursovod"],
    "Management in Tourism and Hospitality": ["upravlyayuschiy-otelem-restoranom"],
    "Ресторанное дело и гостиничный бизнес": ["upravlyayuschiy-otelem-restoranom"],
    "Ресторанный и гостиничный бизнес": ["upravlyayuschiy-otelem-restoranom"],
    "Ресторанный и отельный бизнес": ["upravlyayuschiy-otelem-restoranom"],
    "Арт-менеджмент": ["event-menedzher"],
    "Арт-менеджмент, продюсирование": ["event-menedzher"],
    "Режиссура, арт-менеджмент": ["rezhisser", "event-menedzher"],
    "Реклама и PR": ["pr-menedzher"],
    "Реклама и маркетинговые коммуникации": ["pr-menedzher"],
    "Связи с общественностью": ["pr-menedzher"],
    "Связь с общественностью": ["pr-menedzher"],
    "PR-Менеджмент": ["pr-menedzher"],
    "Маркетинг": ["direktor-po-marketingu"],
    "Marketing": ["direktor-po-marketingu"],
    "Бизнес и маркетинг": ["direktor-po-marketingu"],
    "Маркетинг и бизнес аналитика": ["direktor-po-marketingu", "analitik-dannyh"],
    "Digital маркетинг": ["direktor-po-marketingu"],
    "Digital-маркетинг": ["direktor-po-marketingu"],
    "IT Маркетинг": ["direktor-po-marketingu"],
    "Аналитика бизнес данных": ["analitik-dannyh"],
    "Аналитика Big data": ["analitik-dannyh"],
    "Big Data Analysis": ["analitik-dannyh"],
    "Content, Marketing and Data Analysis (Media)": ["direktor-po-marketingu"],
    "Бизнес аналитика и искусственный интеллект": ["analitik-dannyh", "spetsialist-po-iskusstvennomu-intellektu"],

    # --- Media / journalism ---
    "Журналистика": ["zhurnalist", "pisatel-kopirayter"],
    "Журналистика: аналитика и расследования": ["zhurnalist"],
    "Digital Journalism": ["zhurnalist"],
    "International Journalism": ["zhurnalist"],
    "Международная журналистика": ["zhurnalist"],
    "Конвергентная журналистика": ["zhurnalist"],
    "Медиакоммуникации": ["zhurnalist"],
    "Новые медиа (New Media)": ["zhurnalist"],
    "Media Technologies": ["zhurnalist"],
    "Политические массовые коммуникации": ["zhurnalist"],
    "Аудиовизуальные устройства и медиапроизводство": ["rezhisser"],
    "Аудиопроизводство": ["rezhisser"],

    # --- Design / art / music / theatre ---
    "Architectural design": ["dizayner-interera", "arhitektor"],
    "Graphic design": ["graficheskiy-dizayner"],
    "Графический дизайн": ["graficheskiy-dizayner"],
    "Графический дизайн (Иллюстрация)": ["graficheskiy-dizayner"],
    "Fashion design": ["modeler"],
    "Мода, дизайн": ["modeler"],
    "Технология моды": ["modeler"],
    "Fashion-индустрия: технологии и конструирование": ["modeler"],
    "Дизайн": ["graficheskiy-dizayner"],
    "Дизайн среды и интерьера": ["dizayner-interera"],
    "Промышленный дизайн": ["graficheskiy-dizayner"],
    "Декоративное искусство": ["hudozhnik"],
    "Декоративное искусство и этнодизайн": ["hudozhnik"],
    "Изобразительное искусство": ["hudozhnik"],
    "Изобразительное искусство и черчение": ["hudozhnik"],
    "Скульптура": ["hudozhnik"],
    "Искусствоведение": ["iskusstvoved"],
    "Ландшафтный дизайн и озеленение": ["landshaftnyy-dizayner"],
    "Факультет управления земельными ресурсами, архитектуры и дизайна": ["arhitektor"],
    "Актерское искусство": ["akter"],
    "Театральное искусство": ["akter"],
    "Режиссура": ["rezhisser"],
    "Режиссура театра": ["rezhisser"],
    "Режиссура кино и телевидения": ["rezhisser"],
    "Режиссура анимации": ["animator-2d-3d"],
    "Режиссура анимационного фильма": ["animator-2d-3d"],
    "Цифровое кинопроизводство (Digital Filmmaking)": ["rezhisser"],
    "Сценография": ["hudozhnik"],
    "Операторское искусство": ["fotograf"],
    "Операторское искусство и фотоискусство": ["fotograf"],
    "Хореография": ["horeograf"],
    "Педагогика хореографии": ["horeograf"],
    "Педагогика хореографического искусства": ["horeograf"],
    "Балетмейстерское искусство": ["horeograf"],
    "Артист балета": ["horeograf"],
    "Артист ансамбля танца": ["horeograf"],
    "Педагогика спортивного бального танца": ["horeograf"],
    "Музыкальное образование": ["prepodavatel-iskusstva"],
    "Музыковедение": ["iskusstvoved"],
    "Композиция": ["muzykant-ispolnitel"],
    "Дирижирование": ["muzykant-ispolnitel"],
    "Дирижирование (оркестровое)": ["muzykant-ispolnitel"],
    "Дирижирование (хоровое)": ["muzykant-ispolnitel"],
    "Дирижирование военно-духовым оркестром": ["muzykant-ispolnitel"],
    "Вокальное искусство": ["muzykant-ispolnitel"],
    "Инструментальное исполнительство": ["muzykant-ispolnitel"],
    "Инструментальное исполнительство (духовые и ударные инструменты)": ["muzykant-ispolnitel"],
    "Инструментальное исполнительство (классическая гитара)": ["muzykant-ispolnitel"],
    "Инструментальное исполнительство (струнные инструменты)": ["muzykant-ispolnitel"],
    "Инструментальное исполнительство (фортепиано)": ["muzykant-ispolnitel"],
    "Традиционное музыкальное искусство": ["muzykant-ispolnitel"],
    "Традиционное музыкальное искусство (домбра)": ["muzykant-ispolnitel"],
    "Традиционное музыкальное искусство (кобыз и баян)": ["muzykant-ispolnitel"],
    "Традиционное музыкальное искусство (народное пение)": ["muzykant-ispolnitel"],
    "Эстрадное искусство": ["muzykant-ispolnitel"],

    # --- Data science / AI ---
    "AI and Machine Learning": ["spetsialist-po-iskusstvennomu-intellektu"],
    "Artificial Intelligence and Frontier Systems (AI+X)": ["spetsialist-po-iskusstvennomu-intellektu"],
    "Data Science": ["analitik-dannyh"],
    "Наука о данных": ["analitik-dannyh"],
    "Искусственный интеллект": ["spetsialist-po-iskusstvennomu-intellektu"],
    "Искусственный интеллект и анализ данных": ["spetsialist-po-iskusstvennomu-intellektu"],
    "Технологии искусственного интеллекта": ["spetsialist-po-iskusstvennomu-intellektu"],
    "Прикладной искусственный интеллект": ["spetsialist-po-iskusstvennomu-intellektu"],
    "Высоконагруженные информационные системы с искусственным интеллектом": ["razrabotchik-programmnogo-obespecheniya"],
    "Статистика": ["analitik-dannyh"],
    "Physical AI": ["spetsialist-po-iskusstvennomu-intellektu"],
    "Smart City / GovTech AI": ["spetsialist-po-iskusstvennomu-intellektu"],
    "FinTech AI": ["spetsialist-po-iskusstvennomu-intellektu"],
    "HealthTech AI": ["spetsialist-po-iskusstvennomu-intellektu"],
    "Аграрный AI": ["spetsialist-po-iskusstvennomu-intellektu"],
    "Промышленный AI": ["spetsialist-po-iskusstvennomu-intellektu"],
    "Fintech and Artificial Intelligence": ["spetsialist-po-iskusstvennomu-intellektu"],

    # --- IT ---
    "Computer Science": ["razrabotchik-programmnogo-obespecheniya"],
    "Компьютерные науки": ["razrabotchik-programmnogo-obespecheniya"],
    "Информатика (Computer science)": ["razrabotchik-programmnogo-obespecheniya"],
    "Информатика": ["razrabotchik-programmnogo-obespecheniya"],
    "Информационные системы и IT-решения по отраслям": ["razrabotchik-programmnogo-obespecheniya"],
    "Computer technology and software": ["razrabotchik-programmnogo-obespecheniya"],
    "Cybersecurity": ["sistemnyy-administrator"],
    "Кибербезопасность": ["sistemnyy-administrator"],
    "Кибербезопасность цифровых систем": ["sistemnyy-administrator"],
    "Кибер безопасность": ["sistemnyy-administrator"],
    "Компьютерная безопасность": ["sistemnyy-administrator"],
    "Сетевая безопасность": ["sistemnyy-administrator"],
    "Системы информационной безопасности": ["sistemnyy-administrator"],
    "Аппаратные средства защиты информации": ["sistemnyy-administrator"],
    "Криптология": ["sistemnyy-administrator"],
    "Software Engineering": ["razrabotchik-programmnogo-obespecheniya"],
    "Инженерия программного обеспечения (Software Engineering)": ["razrabotchik-programmnogo-obespecheniya"],
    "Программная инженерия": ["razrabotchik-programmnogo-obespecheniya"],
    "Разработка программного обеспечения и защита информации": ["razrabotchik-programmnogo-obespecheniya"],
    "Вычислительная техника и программное обеспечение": ["razrabotchik-programmnogo-obespecheniya"],
    "Вычислительная инженерия": ["razrabotchik-programmnogo-obespecheniya"],
    "Компьютерная инженерия": ["razrabotchik-programmnogo-obespecheniya"],
    "Информационные системы": ["sistemnyy-analitik", "administrator-baz-dannyh"],
    "Информационно-программные системы": ["razrabotchik-programmnogo-obespecheniya"],
    "Информационных технологий": ["razrabotchik-programmnogo-obespecheniya"],
    "IT-технологии в сфере сервиса": ["spetsialist-tehnicheskoy-podderzhki"],
    "IT-направления": ["razrabotchik-programmnogo-obespecheniya"],
    "IT-юрист": ["yurist-advokat"],
    "IT Design": ["graficheskiy-dizayner"],
    "IT Энергетика": ["razrabotchik-programmnogo-obespecheniya"],
    "Цифровые технологии в агропромышленном комплексе": ["razrabotchik-programmnogo-obespecheniya"],
    "Цифровые агросистемы и комплексы": ["razrabotchik-programmnogo-obespecheniya"],
    "Цифровая энергетика": ["razrabotchik-programmnogo-obespecheniya"],
    "Телекоммуникация": ["sistemnyy-administrator"],
    "Телекоммуникационные сети и системы": ["sistemnyy-administrator"],
    "Телекоммуникационные системы и сети": ["sistemnyy-administrator"],
    "Телекоммуникационные системы и сети ж.д.связи": ["sistemnyy-administrator"],
    "Телематика": ["sistemnyy-administrator"],
    "Радиотехнические системы передачи информации": ["sistemnyy-administrator"],
    "Mobile computing (Мобильные вычисления)": ["razrabotchik-programmnogo-obespecheniya"],
    "Industrial Internet of Things": ["razrabotchik-programmnogo-obespecheniya"],
    "Smart Technologies": ["sistemnyy-administrator"],
    "Smart технологии": ["sistemnyy-administrator"],
    "Smart Security Technologies": ["sistemnyy-administrator"],
    "Информационные технологии и защита данных": ["sistemnyy-administrator"],
    "Факультет компьютерных систем и профессионального образования": ["razrabotchik-programmnogo-obespecheniya"],

    # --- Construction / architecture ---
    "Civil Engineering": ["inzhener-stroitel"],
    "Civil and Environmental Engineering": ["inzhener-stroitel"],
    "Архитектура": ["arhitektor"],
    "Архитектурно-строительный": ["inzhener-stroitel"],
    "Промышленное и гражданское строительство": ["inzhener-stroitel"],
    "Строительство": ["inzhener-stroitel", "geodezist"],
    "Технология промышленного и гражданского строительства": ["inzhener-stroitel"],
    "Строительство автомобильных дорог и аэродромов": ["inzhener-stroitel"],
    "Строительство мостов и тоннелей": ["inzhener-stroitel"],
    "Транспортное строительство": ["inzhener-stroitel"],
    "Строительство газонефтепроводов и газонефтехранилищ": ["burovoy-inzhener-neftegazovoe-delo", "inzhener-stroitel"],
    "Водоснабжение и канализация": ["inzhener-stroitel"],
    "Теплогазоснабжение и вентиляция": ["inzhener-stroitel"],
    "Расчет и проектирование зданий и сооружений": ["inzhener-stroitel", "arhitektor"],
    "Инженерия строительных материалов и управление качеством": ["inzhener-stroitel"],
    "Инновационное производство строительных материалов": ["inzhener-stroitel"],
    "Информационные технологии в строительстве": ["inzhener-stroitel"],

    # --- Mechanical / industrial engineering ---
    "Robotics Engineering": ["inzhener-mehanik"],
    "Интеллектуальная робототехника": ["inzhener-mehanik"],
    "Робототехника и мехатроника": ["inzhener-mehanik"],
    "Mechatronics Робототехника": ["inzhener-mehanik"],
    "Контрольно-измерительные приборы и системы в робототехнике": ["inzhener-mehanik"],
    "Chemical and Materials Engineering": ["himik"],
    "Mechanical and Aerospace Engineering": ["inzhener-mehanik"],
    "Машиностроение": ["inzhener-mehanik"],
    "Технологические машины и оборудование": ["inzhener-mehanik"],
    "Технологические машины и оборудование (по отраслям)": ["inzhener-mehanik"],
    "Приборостроение": ["inzhener-mehanik"],
    "Автоматизация и управление": ["inzhener-mehanik"],
    "Process Engineering": ["inzhener-mehanik"],
    "Безопасность жизнедеятельности": ["spasatel-mchs"],
    "Безопасность жизнедеятельности и защита окружающей среды": ["spasatel-mchs", "inzhener-ekolog"],
    "Агроинженерия": ["inzhener-mehanik"],
    "Механическая инженерия": ["inzhener-mehanik"],

    # --- Electrical / power engineering ---
    "Electrical and Computer Engineering": ["inzhener-elektrik"],
    "Electronic Engineering": ["inzhener-elektrik"],
    "Electronic and Electrical Engineering": ["inzhener-elektrik"],
    "Электротехническая инженерия": ["inzhener-elektrik"],
    "Электроэнергетика": ["inzhener-elektrik"],
    "Energy and Environmental Engineering (Энергетика и экологическая инженерия)": ["inzhener-elektrik"],
    "Digital Technologies in Nuclear Power Engineering": ["inzhener-elektrik"],
    "Теплоэнергетика": ["inzhener-elektrik"],
    "Теплоэнергетическая инженерия": ["inzhener-elektrik"],
    "Наземный электрический транспорт и зарядная инфраструктура": ["inzhener-elektrik"],
    "Энергетическая и экологическая техника": ["inzhener-elektrik"],
    "Энергообеспечение сельского хозяйства": ["inzhener-elektrik"],
    "Информационные технологии в электроэнергетике": ["inzhener-elektrik"],
    "Радиотехника и электроника": ["inzhener-elektrik"],
    "Радиотехника, электроника и телекоммуникации": ["inzhener-elektrik"],
    "Транспортно-энергетический": ["inzhener-elektrik"],

    # --- Oil / gas / mining / geology ---
    "Geology": ["geolog"],
    "Geology/Exploration Geology": ["geolog"],
    "Геология и разведка месторождений": ["geolog"],
    "Геология и разведка месторождений полезных ископаемых": ["geolog"],
    "Геология и разведка ресурсов": ["geolog"],
    "Mining and Minerals Engineering": ["geolog"],
    "Горное дело": ["geolog"],
    "Petroleum Engineering": ["burovoy-inzhener-neftegazovoe-delo"],
    "Нефтегазовое дело": ["burovoy-inzhener-neftegazovoe-delo"],
    "Нефтяная инженерия": ["burovoy-inzhener-neftegazovoe-delo"],
    "Нефтяная инженерия (UPC)": ["burovoy-inzhener-neftegazovoe-delo"],
    "Нефтяная техника": ["burovoy-inzhener-neftegazovoe-delo"],
    "Урановое дело": ["geolog"],
    "Технология редких и радиоактивных элементов": ["himik"],
    "Сейсмология": ["geolog"],

    # --- Transport / aviation engineering ---
    "Транспорт, транспортная техника и технологии": ["inzhener-mehanik"],
    "Интеллектуальные технологии транспортных процессов": ["inzhener-mehanik"],
    "Инженерия подвижного состава": ["mashinist-lokomotiva"],
    "Автомобили, путевые и строительные машины": ["inzhener-mehanik"],
    "Организация дорожного движения": ["direktor-po-logistike"],
    "Организация и безопасность дорожного движения": ["direktor-po-logistike"],
    "Организация перевозок, движения и эксплуатации транспорта": ["direktor-po-logistike"],
    "Организация перевозок, движения и эксплуатация транспорта": ["direktor-po-logistike"],
    "Судовождение": ["mashinist-lokomotiva"],
    "Эксплуатация судовых энергетических установок": ["inzhener-elektrik"],
    "Дроны и автономные системы": ["inzhener-mehanik"],
    "Обеспечение авиационной безопасности": ["aviadispetcher"],
    "Организация авиационных перевозок": ["direktor-po-logistike"],
    "Организация аэропортовой деятельности": ["aviadispetcher"],
    "Обслуживание воздушного движения и аэронавигационное обеспечение полетов": ["aviadispetcher"],
    "Обслуживание наземного радиоэлектронного оборудования аэропортов": ["inzhener-elektrik"],
    "Летная эксплуатация гражданских вертолётов (пилот)": ["pilot-grazhdanskoy-aviatsii"],
    "Летная эксплуатация гражданских самолётов (пилот)": ["pilot-grazhdanskoy-aviatsii"],
    "Лётная эксплуатация воздушного транспорта (пилот)": ["pilot-grazhdanskoy-aviatsii"],
    "Техническая эксплуатация летательных аппаратов и двигателей": ["inzhener-mehanik"],
    "Техническая эксплуатация систем авионики летательных аппаратов": ["inzhener-mehanik"],
    "Технология транспортных процессов в авиации": ["aviadispetcher"],

    # --- Natural sciences / research ---
    "Mathematics": ["matematik"],
    "Mathematical and Computational Science": ["matematik"],
    "Математика": ["matematik"],
    "Прикладная математика": ["matematik"],
    "Прикладная математика и информатика": ["matematik"],
    "Инженерная Математика": ["matematik"],
    "Механико-математический": ["matematik"],
    "Математическое и компьютерное моделирование": ["matematik"],
    "Экономико-математическое и компьютерное моделирование": ["matematik", "ekonomist-analitik"],
    "Physics": ["matematik"],
    "Физика": ["matematik"],
    "Астрофизика": ["matematik"],
    "Chemistry": ["himik"],
    "Химия": ["himik"],
    "Химическая технология органических веществ": ["himik", "tehnolog-pischevogo-proizvodstva"],

    # --- Production technology (food / textile / materials) ---
    "Технология продовольственных продуктов": ["tehnolog-pischevogo-proizvodstva"],
    "Технология пищевых продуктов": ["tehnolog-pischevogo-proizvodstva"],
    "Технология продовольственных продуктов (по отраслям)": ["tehnolog-pischevogo-proizvodstva"],
    "Технология перерабатывающих производств (по отраслям)": ["tehnolog-pischevogo-proizvodstva"],
    "Нанотехнология текстиля": ["modeler"],
    "Технология и конструирование изделий легкой промышленности": ["modeler"],
    "Технология и конструирование изделий лёгкой промышленности": ["modeler"],
    "Стандартизация и сертификация": ["spetsialist-po-standartizatsii-i-sertifikatsii"],
    "Стандартизация и сертификация (по отраслям)": ["spetsialist-po-standartizatsii-i-sertifikatsii"],
    "Стандартизация, метрология и сертификация (по пищевой отрасли)": ["spetsialist-po-standartizatsii-i-sertifikatsii", "tehnolog-pischevogo-proizvodstva"],
    "Стандартизация, сертификация и метрология": ["spetsialist-po-standartizatsii-i-sertifikatsii"],

    # --- Added for the 48 missing KZ universities (docs/university-module-fix-plan.md A3/A9) ---
    "3D Animation and Visual Effects": ["animator-2d-3d"],
    "AI specialization": ["spetsialist-po-iskusstvennomu-intellektu"],
    "Acting for Film": ["akter"],
    "Aircraft Construction and Testing": ["inzhener-mehanik"],
    "Analysis and Modeling of Socio-Economic and Business Processes": ["ekonomist-analitik", "matematik"],
    "Biotechnical and Medical Systems and Devices": ["issledovatel-v-oblasti-biotehnologiy"],
    "Business Administration - Global Logistics": ["direktor-po-logistike"],
    "Business Analytics": ["analitik-dannyh"],
    "Computing Systems and Technologies": ["razrabotchik-programmnogo-obespecheniya"],
    "Economics and Management": ["ekonomist-analitik"],
    "Filmmaking": ["rezhisser"],
    "Financial Economics and Financial Technologies": ["finansovyy-analitik"],
    "International Business": ["predprinimatel"],
    "MBA Global Business (Executive)": ["predprinimatel"],
    "Mathematical and Software Support for Information Systems": ["razrabotchik-programmnogo-obespecheniya"],
    "Mining Engineering": ["geolog"],
    "Screenwriting": ["pisatel-kopirayter"],
    "Агробиология": ["agronom"],
    "Аквакультура": ["veterinar"],
    "Английский язык": ["shkolnyy-uchitel"],
    "Банковское дело и финансы": ["finansovyy-konsultant"],
    "Бизнес-администрирование": ["predprinimatel", "sekretar-deloproizvoditel", "spetsialist-po-kadrovomu-deloproizvodstvu"],
    "Бурение скважин": ["burovoy-inzhener-neftegazovoe-delo"],
    "Бухгалтерия": ["buhgalter"],
    "Бухгалтерия и аудит": ["buhgalter", "auditor"],
    "Бухгалтерский учет": ["buhgalter"],
    "Бухгалтерский учёт": ["buhgalter"],
    "Вагонное хозяйство": ["mashinist-lokomotiva"],
    "Ветеринария": ["veterinar"],
    "Геодезия и картография": ["geodezist"],
    "Геология": ["geolog"],
    "Гидротехническое строительство в водном хозяйстве": ["inzhener-stroitel"],
    "Добыча полезных ископаемых": ["geolog"],
    "Дошкольное образование": ["vospitatel-detskogo-sada"],
    "Защита растений": ["agronom"],
    "Защищенные высокопроизводительные вычислительные системы": ["sistemnyy-administrator"],
    "Зоотехния": ["veterinar", "upravlyayuschiy-fermerskim-hozyaystvom"],
    "Инженерные системы водоснабжения": ["inzhener-stroitel"],
    "Информационные системы и связь": ["sistemnyy-analitik", "administrator-baz-dannyh"],
    "Информационные технологии": ["razrabotchik-programmnogo-obespecheniya"],
    "Инфраструктура трубопроводов": ["burovoy-inzhener-neftegazovoe-delo", "inzhener-stroitel"],
    "История Казахстана": ["shkolnyy-uchitel"],
    "История и образование": ["shkolnyy-uchitel"],
    "Казахский язык": ["shkolnyy-uchitel"],
    "Компьютерные науки с искусственным интеллектом": ["razrabotchik-programmnogo-obespecheniya", "spetsialist-po-iskusstvennomu-intellektu"],
    "Культурология": ["prepodavatel-vuza"],
    "Логистика": ["direktor-po-logistike"],
    "Локомотивное хозяйство": ["mashinist-lokomotiva"],
    "Машины и аппараты химических производств": ["inzhener-mehanik"],
    "Машины энергетического оборудования": ["inzhener-mehanik"],
    "Международный бизнес-менеджмент": ["predprinimatel"],
    "Методика обучения начальных классов": ["shkolnyy-uchitel"],
    "Механизация сельского хозяйства": ["inzhener-mehanik"],
    "Немецкий язык": ["shkolnyy-uchitel"],
    "Обогащение полезных ископаемых": ["geolog"],
    "Обработка полезных ископаемых": ["geolog"],
    "Обществоведение": ["shkolnyy-uchitel"],
    "Обществознание": ["shkolnyy-uchitel"],
    "Организация движения": ["direktor-po-logistike"],
    "Организация транспорта и логистика": ["direktor-po-logistike"],
    "Педагогика и искусство": ["prepodavatel-iskusstva"],
    "Переводоведение": ["biznes-perevodchik"],
    "Пищевая инженерия": ["tehnolog-pischevogo-proizvodstva"],
    "Пищевая технология": ["tehnolog-pischevogo-proizvodstva"],
    "Почвоведение": ["agronom"],
    "Право": ["yurist-advokat"],
    "Практическая психология": ["psiholog-konsultant"],
    "Преподавание языков и литературы": ["shkolnyy-uchitel"],
    "Профессиональное образование": ["shkolnyy-uchitel"],
    "Путейское хозяйство": ["inzhener-stroitel"],
    "Разработка месторождений нефти и газа": ["burovoy-inzhener-neftegazovoe-delo"],
    "Реклама и цифровой маркетинг": ["pr-menedzher", "direktor-po-marketingu"],
    "Сельское хозяйство": ["agronom"],
    "Сети связи": ["sistemnyy-administrator"],
    "Системы автоматизации": ["inzhener-mehanik"],
    "Специальная педагогика и психология": ["logoped"],
    "Специальное образование": ["logoped"],
    "Спортивная подготовка": ["trener-po-sportu"],
    "Стандартизация": ["spetsialist-po-standartizatsii-i-sertifikatsii"],
    "Сценическое искусство": ["akter"],
    "Театр": ["akter"],
    "Текстильная технология": ["modeler"],
    "Телекоммуникации": ["sistemnyy-administrator"],
    "Телекоммуникационные технологии": ["sistemnyy-administrator"],
    "Техническая механика": ["inzhener-mehanik"],
    "Технология машиностроения": ["inzhener-mehanik"],
    "Техносферная безопасность": ["spasatel-mchs"],
    "Транспортные системы": ["direktor-po-logistike"],
    "Управление информационными технологиями": ["sistemnyy-analitik"],
    "Физика элементарных частиц и космофизика": ["matematik"],
    "Физическая культура": ["trener-po-sportu", "shkolnyy-uchitel"],
    "Филология и журналистика": ["zhurnalist", "biznes-perevodchik"],
    "Филология иностранных языков": ["biznes-perevodchik", "shkolnyy-uchitel"],
    "Финансовая экономика": ["finansovyy-konsultant", "ekonomist-analitik"],
    "Французский язык": ["shkolnyy-uchitel"],
    "Химическая технология": ["himik"],
    "Художественное образование": ["prepodavatel-iskusstva"],
    "Экология и безопасность технолога": ["inzhener-ekolog"],
    "Экономика и аудит": ["ekonomist-analitik", "auditor"],
    "Электротехника": ["inzhener-elektrik"],
    "Энергетика": ["inzhener-elektrik"],
    "Энергосистемы": ["inzhener-elektrik"],
}

# --- 2026-08-27: coverage for the 53 professions added to
# scripts/riasec_professions.py after the map above (originally 92 professions)
# was written. Kept as a separate additive dict and merged into
# SPECIALTY_TO_PROFESSIONS at import time, NOT edited into the entries above, so:
#   * the new mappings stay reviewable as one unit;
#   * a key that already exists can't be silently dropped by a duplicate literal
#     (a real Python footgun — last dict key wins);
#   * seed_kz_universities.py needs no change — it still just reads
#     SPECIALTY_TO_PROFESSIONS.
# Each list holds ONLY the slugs to ADD; the merge loop below appends them to the
# existing list (deduped) or creates the key. Same rule as the rest of the file:
# a specialty is listed under a profession only when it genuinely trains for it,
# not by shared category. `voennyy-ofitser` is deliberately absent — no civilian
# bachelor specialty in university-data/*.py trains an army officer, and the
# module docstring prefers leaving it in the "unmapped" report over a forced fit.
_ADDITIONAL_SPECIALTY_PROFESSIONS: dict[str, list[str]] = {
    # --- IT: roles that share the CS/SE/IS specialties ---
    "Информационные системы": ["data-engineer"],
    "Информационные системы и связь": ["data-engineer"],
    "Наука о данных": ["data-engineer"],
    "Data Science": ["data-engineer"],
    "Economics and Data Science": ["data-engineer"],
    "Экономика и наука о данных": ["data-engineer"],
    "Вычислительная техника и программное обеспечение": ["devops-inzhener", "qa-inzhener-testirovschik"],
    "Компьютерная инженерия": ["devops-inzhener"],
    "Вычислительная инженерия": ["devops-inzhener"],
    "Computing Systems and Technologies": ["devops-inzhener"],
    "Computer technology and software": ["devops-inzhener", "qa-inzhener-testirovschik"],
    "Программная инженерия": ["mobile-razrabotchik", "qa-inzhener-testirovschik"],
    "Software Engineering": ["mobile-razrabotchik", "qa-inzhener-testirovschik"],
    "Инженерия программного обеспечения (Software Engineering)": ["mobile-razrabotchik", "qa-inzhener-testirovschik"],
    "Mobile computing (Мобильные вычисления)": ["mobile-razrabotchik"],
    "Разработка программного обеспечения и защита информации": ["qa-inzhener-testirovschik"],
    "Информационно-программные системы": ["mobile-razrabotchik", "qa-inzhener-testirovschik"],
    "Mathematical and Software Support for Information Systems": ["qa-inzhener-testirovschik"],
    "Computer Science": ["mobile-razrabotchik"],
    "Компьютерные науки": ["mobile-razrabotchik"],
    "Информатика (Computer science)": ["mobile-razrabotchik"],
    # --- IT: management / design roles ---
    "IT-менеджмент": ["prodakt-menedzher"],
    "IT Management": ["prodakt-menedzher"],
    "IT в бизнесе": ["prodakt-menedzher"],
    "IT (Information Technology, бизнес-профиль)": ["prodakt-menedzher"],
    "Информационные бизнес-системы": ["prodakt-menedzher"],
    "Информационные системы в бизнесе": ["prodakt-menedzher"],
    "Управление информационными технологиями": ["prodakt-menedzher"],
    "Графический дизайн": ["ux-ui-dizayner", "illyustrator"],
    "Графический дизайн (Иллюстрация)": ["ux-ui-dizayner", "illyustrator"],
    "Дизайн": ["ux-ui-dizayner"],
    "Промышленный дизайн": ["ux-ui-dizayner"],
    "IT Design": ["ux-ui-dizayner"],
    "3D Animation and Visual Effects": ["geymdizayner"],
    "Режиссура анимации": ["geymdizayner"],
    "Режиссура анимационного фильма": ["geymdizayner"],
    "Медиакоммуникации": ["tehnicheskiy-pisatel"],

    # --- Law: a law bachelor is the educational path to all of these ---
    "Юриспруденция": ["sudya", "prokuror", "notarius", "mediator-konfliktolog"],
    "Law (Юриспруденция)": ["sudya", "prokuror", "notarius"],
    "Юридический": ["sudya", "prokuror", "notarius"],
    "Право": ["sudya", "prokuror", "notarius"],
    "Цифровая юриспруденция": ["sudya", "notarius"],
    "Юриспруденция: предпринимательское право": ["notarius"],
    "Корпоративное право": ["notarius"],
    "Судебно-прокурорская деятельность": ["prokuror", "sudya"],
    "Следственно-криминалистическая деятельность": ["sudmedekspert-kriminalist"],
    "Право и правоохранительная деятельность": ["sudmedekspert-kriminalist"],
    "Правоохранительная деятельность": ["sudmedekspert-kriminalist"],
    "Юриспруденция: правоохранительная деятельность": ["sudmedekspert-kriminalist"],
    "Социология": ["mediator-konfliktolog"],

    # --- Medicine / biology ---
    "Общая медицина": ["hirurg", "psihiatr", "pediatr"],
    "Педиатрия": ["pediatr"],
    '6-летняя программа "Doctor of Medicine" (Undergraduate Medical Program)': ["hirurg", "psihiatr", "pediatr"],
    "Bachelor of Medical Science": ["hirurg", "psihiatr"],
    "Клиническая психология": ["psihiatr"],
    "Медицинская биология": ["genetik", "neyrobiolog", "meditsinskiy-laboratornyy-tehnolog"],
    "Медико-профилактическое дело": ["epidemiolog", "meditsinskiy-laboratornyy-tehnolog"],
    "Общественное здравоохранение": ["epidemiolog", "nutritsiolog-dietolog"],
    "Общественное здоровье": ["epidemiolog", "nutritsiolog-dietolog"],
    "Биология": ["genetik", "neyrobiolog"],
    "Biological Sciences": ["genetik", "neyrobiolog"],
    "Биофизика": ["neyrobiolog"],
    "Биоинженерия и биоинформатика": ["genetik"],
    "Биотехнология": ["genetik"],
    "Когнитивные науки": ["neyrobiolog"],
    "Технология продовольственных продуктов": ["nutritsiolog-dietolog"],
    "Технология пищевых продуктов": ["nutritsiolog-dietolog"],
    "Пищевая технология": ["nutritsiolog-dietolog"],
    "Пищевая инженерия": ["nutritsiolog-dietolog"],

    # --- Natural sciences ---
    "Физика": ["fizik", "astronom"],
    "Physics": ["fizik", "astronom"],
    "Астрофизика": ["astronom", "fizik"],
    "Физика элементарных частиц и космофизика": ["fizik", "astronom"],
    "География": ["okeanolog-gidrolog"],
    "Экология": ["okeanolog-gidrolog"],
    "Водное хозяйство и мелиорация": ["okeanolog-gidrolog"],
    "Гидротехническое строительство в водном хозяйстве": ["okeanolog-gidrolog"],

    # --- Engineering: constructor / manufacturing technologist / automation ---
    "Машиностроение": ["inzhener-konstruktor", "inzhener-tehnolog-mashinostroenie"],
    "Технология машиностроения": ["inzhener-tehnolog-mashinostroenie", "inzhener-konstruktor"],
    "Технологические машины и оборудование": ["inzhener-tehnolog-mashinostroenie", "inzhener-konstruktor"],
    "Технологические машины и оборудование (по отраслям)": ["inzhener-tehnolog-mashinostroenie", "inzhener-konstruktor"],
    "Приборостроение": ["inzhener-konstruktor"],
    "Техническая механика": ["inzhener-konstruktor"],
    "Механическая инженерия": ["inzhener-konstruktor"],
    "Aircraft Construction and Testing": ["inzhener-konstruktor"],
    "Robotics Engineering": ["inzhener-po-avtomatizatsii-i-robototehnike"],
    "Интеллектуальная робототехника": ["inzhener-po-avtomatizatsii-i-robototehnike"],
    "Робототехника и мехатроника": ["inzhener-po-avtomatizatsii-i-robototehnike"],
    "Mechatronics Робототехника": ["inzhener-po-avtomatizatsii-i-robototehnike"],
    "Контрольно-измерительные приборы и системы в робототехнике": ["inzhener-po-avtomatizatsii-i-robototehnike"],
    "Автоматизация и управление": ["inzhener-po-avtomatizatsii-i-robototehnike"],
    "Системы автоматизации": ["inzhener-po-avtomatizatsii-i-robototehnike"],

    # --- Engineering: chemical / power / mining / metallurgy ---
    "Химическая технология": ["inzhener-himik"],
    "Химическая технология органических веществ": ["inzhener-himik"],
    "Chemical and Materials Engineering": ["inzhener-himik"],
    "Машины и аппараты химических производств": ["inzhener-himik"],
    "Технология редких и радиоактивных элементов": ["inzhener-himik", "metallurg"],
    "Электроэнергетика": ["inzhener-energetik"],
    "Теплоэнергетика": ["inzhener-energetik"],
    "Теплоэнергетическая инженерия": ["inzhener-energetik"],
    "Энергетика": ["inzhener-energetik"],
    "Энергосистемы": ["inzhener-energetik"],
    "Энергетическая и экологическая техника": ["inzhener-energetik"],
    "Горное дело": ["gornyy-inzhener"],
    "Mining and Minerals Engineering": ["gornyy-inzhener"],
    "Mining Engineering": ["gornyy-inzhener"],
    "Добыча полезных ископаемых": ["gornyy-inzhener"],
    "Обогащение полезных ископаемых": ["gornyy-inzhener", "metallurg"],
    "Обработка полезных ископаемых": ["gornyy-inzhener", "metallurg"],

    # --- Cybersecurity engineer (distinct from sysadmin-flavoured infosec) ---
    "Cybersecurity": ["inzhener-po-kiberbezopasnosti"],
    "Кибербезопасность": ["inzhener-po-kiberbezopasnosti"],
    "Кибербезопасность цифровых систем": ["inzhener-po-kiberbezopasnosti"],
    "Кибер безопасность": ["inzhener-po-kiberbezopasnosti"],
    "Компьютерная безопасность": ["inzhener-po-kiberbezopasnosti"],
    "Сетевая безопасность": ["inzhener-po-kiberbezopasnosti"],
    "Системы информационной безопасности": ["inzhener-po-kiberbezopasnosti"],
    "Информационные технологии и защита данных": ["inzhener-po-kiberbezopasnosti"],
    "Криптология": ["inzhener-po-kiberbezopasnosti"],

    # --- Creative: sound / illustration / screenwriting / stylist ---
    "Аудиопроизводство": ["zvukorezhisser"],
    "Аудиовизуальные устройства и медиапроизводство": ["zvukorezhisser"],
    "Эстрадное искусство": ["zvukorezhisser"],
    "Изобразительное искусство": ["illyustrator"],
    "Изобразительное искусство и черчение": ["illyustrator"],
    "Декоративное искусство": ["illyustrator"],
    "Screenwriting": ["stsenarist"],
    "Режиссура кино и телевидения": ["stsenarist"],
    "Цифровое кинопроизводство (Digital Filmmaking)": ["stsenarist"],
    "Filmmaking": ["stsenarist"],
    "Fashion design": ["modnyy-stilist"],
    "Мода, дизайн": ["modnyy-stilist"],
    "Технология моды": ["modnyy-stilist"],
    "Fashion-индустрия: технологии и конструирование": ["modnyy-stilist"],
    "Композиция": ["kompozitor"],
    "Музыковедение": ["kompozitor"],
    "Музыкальное образование": ["kompozitor"],

    # --- Finance: investment banker / financial controller ---
    "Финансы": ["investitsionnyy-bankir", "finansovyy-kontroler"],
    "Finance": ["investitsionnyy-bankir", "finansovyy-kontroler"],
    "Финансы и инвестиции": ["investitsionnyy-bankir"],
    "Финансовые рынки и финансовые институты": ["investitsionnyy-bankir"],
    "Банковское дело и финансы": ["investitsionnyy-bankir"],
    "Financial Economics and Financial Technologies": ["investitsionnyy-bankir"],
    "Корпоративные финансы": ["investitsionnyy-bankir", "finansovyy-kontroler"],
    "Финансовая аналитика": ["finansovyy-kontroler"],
    "Учет и аудит": ["finansovyy-kontroler"],
    "Учёт и аудит": ["finansovyy-kontroler"],
    "Учет и Аудит": ["finansovyy-kontroler"],
    "Учет и аудит по ACCA": ["finansovyy-kontroler"],
    "Бухгалтерский учет и аудит": ["finansovyy-kontroler"],
    "Бухгалтерский учет и финансы": ["finansovyy-kontroler"],
    "Экономика и аудит": ["finansovyy-kontroler"],

    # --- Marketing / logistics: broaden from the "director" role to the IC role ---
    "Маркетинг": ["marketolog"],
    "Marketing": ["marketolog"],
    "Бизнес и маркетинг": ["marketolog"],
    "Менеджмент и маркетинг": ["marketolog"],
    "Digital маркетинг": ["marketolog"],
    "Digital-маркетинг": ["marketolog"],
    "IT Маркетинг": ["marketolog"],
    "Маркетинг и бизнес аналитика": ["marketolog"],
    "Реклама и маркетинговые коммуникации": ["marketolog"],
    "Реклама и цифровой маркетинг": ["marketolog"],
    "Логистика": ["logist"],
    "Логистика (по отраслям)": ["logist"],
    "Транспортная логистика": ["logist"],
    "Производственная логистика": ["logist"],
    "Цифровая логистика": ["logist"],
    "Логистика на транспорте": ["logist"],
    "Logistics (Логистика)": ["logist"],
    "Организация перевозок и логистика на транспорте": ["logist"],
    "Организация транспорта и логистика": ["logist"],
    "Транспортные системы": ["logist"],
    "Business Administration - Global Logistics": ["logist"],

    # --- Psychology / pedagogy / social ---
    "Педагогика и психология": ["pedagog-psiholog", "proforientolog-karernyy-konsultant"],
    "Педагогика и психология с полиязычием": ["pedagog-psiholog"],
    "Психологические особенности развития личности": ["pedagog-psiholog"],
    "Специальная педагогика и психология": ["pedagog-psiholog", "defektolog"],
    "Специальное образование": ["defektolog"],
    "Дефектология": ["defektolog"],
    "Психология": ["proforientolog-karernyy-konsultant"],
    "Практическая психология": ["proforientolog-karernyy-konsultant"],
    "Организационная психология": ["proforientolog-karernyy-konsultant"],
    "Психологическое консультирование": ["proforientolog-karernyy-konsultant"],
    "Социальная работа": ["mediator-konfliktolog"],

    # --- Sport management / agency ---
    "Физическая культура и спорт": ["sportivnyy-menedzher-agent"],
    "Физическая культура": ["sportivnyy-menedzher-agent"],
    "Спортивная подготовка": ["sportivnyy-menedzher-agent"],
    "Фитнес и рекреация": ["sportivnyy-menedzher-agent"],

    # --- Humanities: historian / linguist / religious-studies scholar / urbanist ---
    "История": ["istorik"],
    "History": ["istorik"],
    "История Казахстана": ["istorik"],
    "История и образование": ["istorik"],
    "Anthropology": ["istorik"],
    "Филология": ["filolog-lingvist"],
    "Филологический": ["filolog-lingvist"],
    "Прикладная лингвистика": ["filolog-lingvist"],
    "Applied Linguistics": ["filolog-lingvist"],
    "Казахский язык и литература": ["filolog-lingvist"],
    "Русский язык и литература": ["filolog-lingvist"],
    "Казахский-английский языки и лингвистика": ["filolog-lingvist"],
    "Религиоведение": ["teolog-religioved"],
    "Исламоведение": ["teolog-religioved"],
    "Теология": ["teolog-religioved"],
    "Архитектура": ["urbanist-gradostroitel"],
    "Архитектурно-строительный": ["urbanist-gradostroitel"],
    "Факультет управления земельными ресурсами, архитектуры и дизайна": ["urbanist-gradostroitel"],
}

for _specialty, _new_slugs in _ADDITIONAL_SPECIALTY_PROFESSIONS.items():
    _current = SPECIALTY_TO_PROFESSIONS.setdefault(_specialty, [])
    for _slug in _new_slugs:
        if _slug not in _current:
            _current.append(_slug)
